### ISSUE TITLE
Versions out of sync

### ISSUE THREAD

**Issue by ryanduffyegov** [apache/grails-gradle-plugin#102]
In JFrog, I see the current version of grails core is 5.1.6 but the current version of grails gradle plugin is 5.1.3.  Are the two compatible or is there going to be a pending release of 5.1.6 for gradle plugin?

**Comment by puneetbehl** [comment]
Please note that Grails Gradle Plugin release may not evolve with same pace of Grails release. Generally, it will be compatible with future Grails releases.
