### ISSUE TITLE
Releases 5.1.4 to 5.1.6 missing?

### ISSUE THREAD

**Issue by Erando89** [apache/grails-gradle-plugin#103]
README.md describes how to add `grails-gradle-plugin` to the gradle dependencies.
```
buildscript {
	dependencies {
		classpath "org.grails:grails-gradle-plugin:$grailsVersion"
	}
}
```
So obviously there's supposed to exist a `grails-gradle-plugin` version for any official grails version.

So I wonder why isn't there a `grails-gradle-plugin` release `5.1.4`, `5.1.5` and `5.1.6`?

**Comment by rainboyan** [comment]
FYI, https://grails.org/blog/2021-10-11-grails-5-ga.html

> The [Grails Gradle Plugin](https://github.com/grails/grails-gradle-plugin) is moved out of grails-core and may follow separate versioning, so you should decouple the grailsVersion Gradle property from grailsGradlePluginVersion in existing applications.

At the present time, `grails-gradle-plugin` not need to be released if without new features updated, I think it should allow us set `springBootVersion` to the new version of Spring Boot,  but unfortunately it do not support this. See #104

**Comment by rainboyan** [comment]
Duplicated with #102
