### ISSUE TITLE
Improvement: allow grails-profile plugin contains groovy source files

### ISSUE THREAD

**Issue by rainboyan** [apache/grails-gradle-plugin#95]
Current version grails profile Gradle plugin don't allow project contain groovy source files, when apply `groovy` plugin, it has below errors. 

```
FAILURE: Build failed with an exception.

* Where:
Build file '/grails-demos/web-profile-command-demo/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'web-profile-command-demo'.
> Failed to apply plugin 'org.grails.grails-profile'.
   > Cannot add task 'processResources' as a task with that name already exists.
```

[Demo project](https://github.com/rainboyan/grails-web-profile-command-demo/tree/improvement_profile_plugin)

Environment:
* Grails 5.1.2
* Java OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)

**Comment by rainboyan** [comment]
I create a Grails Profile project which contains custom `Step` and `Command`, it's a very useful feature since Grails 3.0. 
I modified some of the code to implement this feature in branch [4.0.x](https://github.com/rainboyan/grails-gradle-plugin/tree/custom_profile), If anyone is interested, discussions and feedback are welcome, and I hope Grails become better and powerful.

**Comment by puneetbehl** [comment]
It seems like one or more Gradle plugins are trying to add a task with same name which is not possible. I would need to look into details for more information. Also, I have noticed that the sample application is using  “org.grails.internal.grails-profile-publish" which is only meant to be used internally by us and not meant for the community. The designs and decision for this plugin are solely based on internal Grails project and may change frequently. So, I would recommend removing it and instead use Gradle “maven-publish” plugin directly for publishing the profiles. 

Another thing is that the sample application is using older version of Grails and Grails Gradle Plugin. I think it would be worth trying to update to latest.

**Comment by rainboyan** [comment]
> It seems like one or more Gradle plugins are trying to add a task with same name which is not possible. I would need to look into details for more information. 

Yes, 'processResources' conflicts with the same task name from Groovy Plugin.

> Another thing is that the sample application is using older version of Grails and Grails Gradle Plugin. I think it would be worth trying to update to latest.

There was another error when updated to 5.1.2, https://github.com/grails/grails-gradle-plugin/issues/94
